use std::path::Path;

use crate::config::CircuitConfig;
use crate::error::Result;

/// Generate the circom source code for a main component.
///
/// The generated file includes the pragma, an include directive
/// (relative from `main/` up to the circuit file), and the
/// `component main` declaration.
pub fn make_circuit_source(config: &CircuitConfig, version: &str) -> String {
    let mut source = String::new();

    source.push_str("// auto-generated by circomkit\n");
    source.push_str(&format!("pragma circom {version};\n"));

    if config.uses_custom_templates {
        source.push_str("pragma custom_templates;\n");
    }

    source.push_str(&format!("include \"../{}.circom\";\n\n", config.file));

    // component main declaration
    source.push_str("component main");

    if !config.pubs.is_empty() {
        source.push_str(&format!(" {{public[{}]}}", config.pubs.join(", ")));
    }

    source.push_str(&format!(
        " = {}({});\n",
        config.template,
        config
            .params
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(", ")
    ));

    source
}

/// Write the main component circom file to disk.
///
/// Creates the target directory if it doesn't exist.
pub fn instantiate_circuit(
    config: &CircuitConfig,
    target_path: &Path,
    version: &str,
) -> Result<()> {
    let source = make_circuit_source(config, version);

    if let Some(parent) = target_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(target_path, source)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn basic_circuit_source() {
        let config = CircuitConfig {
            file: "multiplier".to_string(),
            template: "Multiplier".to_string(),
            pubs: vec![],
            params: vec![serde_json::json!(3)],
            uses_custom_templates: false,
            overrides: None,
        };

        let source = make_circuit_source(&config, "2.1.0");
        assert!(source.contains("pragma circom 2.1.0;"));
        assert!(source.contains("include \"../multiplier.circom\";"));
        assert!(source.contains("component main = Multiplier(3);"));
        assert!(!source.contains("custom_templates"));
    }

    #[test]
    fn circuit_with_public_signals() {
        let config = CircuitConfig {
            file: "arrays".to_string(),
            template: "Arrays".to_string(),
            pubs: vec!["in1D".to_string(), "in2D".to_string()],
            params: vec![serde_json::json!(2), serde_json::json!(3)],
            uses_custom_templates: false,
            overrides: None,
        };

        let source = make_circuit_source(&config, "2.1.0");
        assert!(source.contains("{public[in1D, in2D]}"));
        assert!(source.contains("= Arrays(2, 3);"));
    }

    #[test]
    fn circuit_with_custom_templates() {
        let config = CircuitConfig {
            file: "custom".to_string(),
            template: "Custom".to_string(),
            pubs: vec![],
            params: vec![],
            uses_custom_templates: true,
            overrides: None,
        };

        let source = make_circuit_source(&config, "2.1.0");
        assert!(source.contains("pragma custom_templates;"));
    }
}
