use std::io::Write;
use std::path::Path;

use num_bigint::BigInt;
use num_traits::Signed;

use super::primes::{prime_field_n8, prime_value};
use crate::error::{CoreError, Result};
use crate::types::Witness;

/// Parse a binary `.wtns` file into witness elements.
///
/// The witness file format (as generated by Circom witness calculators):
/// - Header: `"wtns"` magic (4 bytes), version (4 bytes LE), num sections (4 bytes LE)
/// - Section 1: field metadata — `n8` (4 bytes LE), prime `q` (n8 bytes LE), num witnesses (4 bytes LE)
/// - Section 2: witness data — `n8` bytes per element
pub fn parse_witness_file(path: &Path) -> Result<Witness> {
    let buffer = std::fs::read(path)?;
    parse_witness_bytes(&buffer)
}

/// Parse witness data from a byte buffer.
pub fn parse_witness_bytes(buffer: &[u8]) -> Result<Witness> {
    parse_witness_to_elems(buffer, BigInt::from_signed_bytes_le)
        .map_err(|e| CoreError::InvalidWitness(e.to_string()))
}

/// Generic witness parser that accepts a conversion function for each field element chunk.
pub fn parse_witness_to_elems<T>(
    buffer: &[u8],
    chunk_to_elem: impl Fn(&[u8]) -> T,
) -> std::io::Result<Vec<T>> {
    let mut pos = 0;

    // Magic bytes: "wtns"
    if buffer.len() < 12 || &buffer[pos..pos + 4] != b"wtns" {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "invalid witness file: missing 'wtns' magic",
        ));
    }
    pos += 4;

    // Version (4 bytes LE)
    let _version = u32::from_le_bytes(buffer[pos..pos + 4].try_into().unwrap());
    pos += 4;

    // Number of sections (4 bytes LE)
    let n_sections = u32::from_le_bytes(buffer[pos..pos + 4].try_into().unwrap());
    pos += 4;

    // Bytes per field element, set when we encounter section 1
    let mut n8: u32 = 0;

    for _ in 0..n_sections {
        if pos + 12 > buffer.len() {
            break;
        }

        let section_id = u32::from_le_bytes(buffer[pos..pos + 4].try_into().unwrap());
        pos += 4;

        let section_length = u64::from_le_bytes(buffer[pos..pos + 8].try_into().unwrap()) as usize;
        pos += 8;

        if pos + section_length > buffer.len() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "section exceeds buffer length",
            ));
        }

        match section_id {
            // Section 1: field metadata
            1 => {
                n8 = u32::from_le_bytes(buffer[pos..pos + 4].try_into().unwrap());
                // Skip the rest (prime q + num witness values)
                pos += section_length;
            }
            // Section 2: witness data
            2 => {
                let elems: Vec<T> = buffer[pos..pos + section_length]
                    .chunks(n8 as usize)
                    .map(&chunk_to_elem)
                    .collect();
                return Ok(elems);
            }
            // Skip unknown sections
            _ => {
                pos += section_length;
            }
        }
    }

    Err(std::io::Error::new(
        std::io::ErrorKind::InvalidData,
        "witness data section not found",
    ))
}

/// Write a witness to a binary `.wtns` file (version 2) for the given prime.
pub fn write_witness_file(
    path: &Path,
    witness: &Witness,
    prime: crate::enums::Prime,
) -> Result<()> {
    let n8 = prime_field_n8(prime);
    let prime_bytes = prime_value(prime).to_bytes_le();

    let witness_count = witness.len() as u32;

    let mut buf = Vec::new();

    // Header
    buf.write_all(b"wtns")?;
    buf.write_all(&2u32.to_le_bytes())?; // version
    buf.write_all(&2u32.to_le_bytes())?; // num sections

    // Section 1: field metadata
    let section1_len: u64 = 4 + (n8 as u64) + 4; // n8 + prime + witness_count
    buf.write_all(&1u32.to_le_bytes())?; // section id
    buf.write_all(&section1_len.to_le_bytes())?;
    buf.write_all(&n8.to_le_bytes())?;

    // Prime (padded to n8 bytes)
    let mut prime_buf = vec![0u8; n8 as usize];
    let len = prime_bytes.len().min(n8 as usize);
    prime_buf[..len].copy_from_slice(&prime_bytes[..len]);
    buf.write_all(&prime_buf)?;

    buf.write_all(&witness_count.to_le_bytes())?;

    // Section 2: witness data
    let section2_len: u64 = (n8 as u64) * (witness_count as u64);
    buf.write_all(&2u32.to_le_bytes())?; // section id
    buf.write_all(&section2_len.to_le_bytes())?;

    for elem in witness {
        let mut elem_buf = vec![0u8; n8 as usize];
        let (_, bytes) = if elem.is_negative() {
            // Shouldn't happen for valid witnesses, but handle gracefully
            elem.to_bytes_le()
        } else {
            elem.to_bytes_le()
        };
        let len = bytes.len().min(n8 as usize);
        elem_buf[..len].copy_from_slice(&bytes[..len]);
        buf.write_all(&elem_buf)?;
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, buf)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::enums::Prime;

    /// Extract the `n8` field from section 1 of a written witness file.
    /// Layout: header (12 bytes) + section id (4) + section length (8) → n8 at offset 24.
    fn n8_from_bytes(buf: &[u8]) -> u32 {
        u32::from_le_bytes(buf[24..28].try_into().unwrap())
    }

    #[test]
    fn writes_n8_per_prime_and_roundtrips() {
        let dir = tempfile::tempdir().unwrap();

        // create a fake witness
        let witness = vec![BigInt::from(1), BigInt::from(42), BigInt::from(255)];

        // bn128 packs elements into 32 bytes
        let bn = dir.path().join("bn128.wtns");
        write_witness_file(&bn, &witness, Prime::Bn128).unwrap();
        let bytes = std::fs::read(&bn).unwrap();
        assert_eq!(n8_from_bytes(&bytes), 32);
        assert_eq!(parse_witness_bytes(&bytes).unwrap(), witness);

        // goldilocks packs elements into 8 bytes
        let gl = dir.path().join("goldilocks.wtns");
        write_witness_file(&gl, &witness, Prime::Goldilocks).unwrap();
        let bytes = std::fs::read(&gl).unwrap();
        assert_eq!(n8_from_bytes(&bytes), 8);
        assert_eq!(parse_witness_bytes(&bytes).unwrap(), witness);
    }
}
