// Ergonomic, typed TypeScript facade over the low-level napi binding.
//
// The Rust binding (`binding.js`, generated by `napi build`) speaks JSON strings
// and is synchronous. This layer wraps it so callers pass plain objects (with
// `bigint` support) and get typed, generic testers.
//
// The package's `main`/`types` point here.

import {
  Circomkit as CircomkitNative,
  type WitnessTester as WitnessTesterNative,
  type ProofTester as ProofTesterNative,
  type Witness,
  type R1CsInfo,
  type SetupResult,
} from "./binding.js";

export type { Witness, R1CsInfo, SetupResult };

// --- config & value types (mirror circomkit.json) --------------------------

export type Prime =
  | "bn128"
  | "bls12381"
  | "goldilocks"
  | "grumpkin"
  | "pallas"
  | "vesta"
  | "secq256r1";
export type Protocol = "groth16" | "plonk" | "fflonk";
export type ProvingBackend = "snarkjs" | "arkworks" | "lambdaworks";
export type WitnessCalculator = "wasm" | "c";

/** A signal value: a field element (number/bigint/decimal string) or a nested array. */
export type SignalValue = number | bigint | string;
export type Signal = SignalValue | Signal[];
/** A map of signal name → value, optionally keyed by a known set of names. */
export type CircuitSignals<S extends string = string> = Record<S, Signal>;

export interface CircuitConfig {
  /** Source file under `srcDir`, without extension. */
  file: string;
  /** Template to instantiate. */
  template: string;
  /** Template parameters. */
  params?: (number | string)[];
  /** Public input signal names. */
  pubs?: string[];
  /** Legacy v0.3 build subdirectory. Accepted for compatibility; ignored. */
  dir?: string;
}

export interface CircomkitConfig {
  prover?: {
    protocol?: Protocol;
    backend?: ProvingBackend;
    ptauDir?: string;
    inputDir?: string;
  };
  compiler?: {
    prime?: Prime;
    srcDir?: string;
    outDir?: string;
    optimization?: number;
  };
  witness?: { calculator?: WitnessCalculator };
  circuits?: Record<string, CircuitConfig>;
  version?: string;
  logLevel?: string;
  /**
   * Legacy v0.3 flat options. A config using these (or top-level `prime` /
   * `protocol` / dir fields) is auto-detected and converted to the nested
   * format, so an old `{ verbose, inspect }` config keeps working.
   */
  verbose?: boolean;
  inspect?: boolean;
}

// --- helpers ---------------------------------------------------------------

/** JSON with `bigint` rendered as decimal strings (what the binding accepts). */
function toJson(x: unknown): string {
  return JSON.stringify(x, (_k, v) =>
    typeof v === "bigint" ? v.toString() : v,
  );
}

// --- testers ---------------------------------------------------------------

/**
 * Witness-level circuit tester. Generic over the input and output signal names
 * for typed assertions, e.g. `WitnessTester<["in"], ["out"]>`.
 */
export class WitnessTester<
  I extends readonly string[] = string[],
  O extends readonly string[] = string[],
> {
  constructor(private readonly inner: WitnessTesterNative) {}

  /** Assert the input produces a valid witness (and, if given, matching outputs). */
  expectPass(
    input: CircuitSignals<I[number]>,
    output?: CircuitSignals<O[number]>,
  ): void {
    if (output) this.inner.expectPassWith(toJson(input), toJson(output));
    else this.inner.expectPass(toJson(input));
  }

  /** Assert the input is rejected; returns the circuit error message. */
  expectFail(input: CircuitSignals<I[number]>): string {
    return this.inner.expectFail(toJson(input));
  }

  /** Assert the constraint count (exact, or a lower bound when `exact` is false). */
  expectConstraintCount(count: number, exact = true): void {
    this.inner.expectConstraintCount(count, exact);
  }

  /** The circuit's constraint count. */
  getConstraintCount(): number {
    return this.inner.constraintCount();
  }

  /** Compute a witness and read the named output signals. */
  compute<S extends string>(
    input: CircuitSignals<I[number]>,
    signals: S[],
  ): CircuitSignals<S> {
    return JSON.parse(this.inner.compute(toJson(input), signals));
  }

  /** R1CS metadata for the circuit. */
  getInfo(): R1CsInfo {
    return this.inner.r1CsInfo();
  }

  /** Compute an opaque witness handle (for soundness testing). */
  calculateWitness(input: CircuitSignals<I[number]>): Witness {
    return this.inner.calculateWitness(toJson(input));
  }

  /** Return a new witness with `symbol → value` overrides applied. */
  editWitness(
    witness: Witness,
    overrides: Record<string, SignalValue>,
  ): Witness {
    return this.inner.editWitness(witness, toJson(overrides));
  }

  /** Read named signal values from a witness handle. */
  readWitnessSignals<S extends string>(
    witness: Witness,
    signals: S[],
  ): CircuitSignals<S> {
    return JSON.parse(this.inner.readWitnessSignals(witness, signals));
  }
}

/** A generated proof and its public signals. */
export interface Proof {
  proof: unknown;
  publicSignals: string[];
}

/** Proof-level circuit tester (run `setup` first). */
export class ProofTester {
  constructor(private readonly inner: ProofTesterNative) {}

  /** Generate a proof. */
  prove(input: CircuitSignals): Proof {
    return JSON.parse(this.inner.prove(toJson(input)));
  }

  /** Verify a proof. */
  verify(proof: unknown, publicSignals: string[]): boolean {
    return this.inner.verify(toJson(proof), publicSignals);
  }

  /** Assert verification passes. */
  expectPass(proof: unknown, publicSignals: string[]): void {
    this.inner.expectPass(toJson(proof), publicSignals);
  }

  /** Assert verification fails. */
  expectFail(proof: unknown, publicSignals: string[]): void {
    this.inner.expectFail(toJson(proof), publicSignals);
  }
}

// --- orchestrator ----------------------------------------------------------

/** A Circom development & testing toolkit instance. */
export class Circomkit {
  private inner: CircomkitNative;
  /** Active config, normalized to the nested format (read back from native). */
  private config: CircomkitConfig;

  /**
   * Construct from a config object. A legacy v0.3 flat config (e.g.
   * `{ verbose, inspect }`) is auto-detected and converted.
   */
  constructor(config: CircomkitConfig = {}) {
    this.inner = CircomkitNative.fromConfig(toJson(config));
    this.config = JSON.parse(this.inner.configJson());
  }

  /** Load from a `circomkit.json` file (legacy configs are converted). */
  static fromFile(path: string): Circomkit {
    const ck = new Circomkit();
    ck.inner = CircomkitNative.fromFile(path);
    ck.config = JSON.parse(ck.inner.configJson());
    return ck;
  }

  /** Load from a config object (alias for the constructor). */
  static fromConfig(config: CircomkitConfig): Circomkit {
    return new Circomkit(config);
  }

  // ---- lifecycle (paths returned as strings) ----

  instantiate(circuit: string): string {
    return this.inner.instantiate(circuit);
  }
  compile(circuit: string): string {
    return this.inner.compile(circuit);
  }
  info(circuit: string): R1CsInfo {
    return this.inner.info(circuit);
  }
  clear(circuit: string): void {
    this.inner.clear(circuit);
  }
  ptau(circuit: string): string {
    return this.inner.ptau(circuit);
  }
  setup(circuit: string, ptauPath?: string): SetupResult {
    return this.inner.setup(circuit, ptauPath);
  }
  vkey(circuit: string): string {
    return this.inner.vkey(circuit);
  }
  contract(circuit: string): string {
    return this.inner.contract(circuit);
  }
  witness(circuit: string, input: string, data?: CircuitSignals): string {
    return this.inner.witness(circuit, input, data ? toJson(data) : undefined);
  }
  prove(
    circuit: string,
    input: string,
    data?: CircuitSignals,
    backend?: ProvingBackend,
  ): string {
    return this.inner.prove(
      circuit,
      input,
      data ? toJson(data) : undefined,
      backend,
    );
  }
  verify(circuit: string, input: string): boolean {
    return this.inner.verify(circuit, input);
  }
  calldata(circuit: string, input: string, pretty?: boolean): string {
    return this.inner.calldata(circuit, input, pretty);
  }
  loadInput(circuit: string, input: string): CircuitSignals {
    return JSON.parse(this.inner.loadInput(circuit, input));
  }

  // ---- testers ----

  /**
   * Create a typed `WitnessTester`. The circuit may come from the loaded config
   * (by name) or be supplied inline; inline config merges onto the base config.
   *
   * Capitalized to match the original (TypeScript) Circomkit API, so existing
   * suites work unchanged.
   */
  WitnessTester<
    I extends readonly string[] = string[],
    O extends readonly string[] = string[],
  >(circuit: string, config?: CircuitConfig): WitnessTester<I, O> {
    if (config) {
      const merged: CircomkitConfig = {
        ...this.config,
        circuits: { ...this.config.circuits, [circuit]: config },
      };
      const native = CircomkitNative.fromConfig(toJson(merged));
      return new WitnessTester(native.witnessTester(circuit));
    }
    return new WitnessTester(this.inner.witnessTester(circuit));
  }

  /** Create a `ProofTester` for a circuit and protocol (run `setup` first). */
  ProofTester(circuit: string, protocol: Protocol = "groth16"): ProofTester {
    return new ProofTester(this.inner.proofTester(circuit, protocol));
  }
}
