<%#'this file is an EJS template to generate main component for circuits'-%>
<%#'configuration is read from config.js in the project root directory'-%>
// auto-generated by instantiate.js
pragma circom 2.0.0;

include "../<%= file %>.circom";

component main<%=
  publicInputs.length == 0 ?
  '' :
  ' {public[' + publicInputs.join(", ") + ']}'
  %> = <%= template %>(<%= templateInputs.join(", ") %>);
