<%#'this file is an EJS template to generate main component for circuits'-%>
<%#'configuration is read from config.js in the project root directory'-%>
<%#'do not edit this file!'-%>
// auto-generated by instantiate.js
pragma circom 2.0.0;

include "../<%= file %>.circom";

component main<%=
  pubs.length == 0 ?
  '' :
  ' {public[' + pubs.join(", ") + ']}'
  %> = <%= template %>(<%= params.join(", ") %>);
