//! Main-component (`component main`) source generation.
//!
//! Generates the small auto-generated `.circom` file that instantiates a
//! circuit's template as its `main` component, including the pragma(s), an
//! `include` of the template file, and the `component main` declaration.
//!
//! This is intentionally decoupled from any config type: callers pass the
//! relevant fields via [`MainComponentSpec`], so this crate depends only on
//! `circomkit-parser` (and `serde_json` for rendering parameters).

use std::path::Path;

use serde_json::Value;

/// The inputs needed to generate a circuit's `main` component file.
pub struct MainComponentSpec<'a> {
    /// Template source filename (relative to `src_dir`, without extension),
    /// e.g. `"multiplier"`. Included as `../<file>.circom`.
    pub file: &'a str,
    /// Name of the circom template to instantiate.
    pub template: &'a str,
    /// Template instantiation parameters, rendered as circom literals.
    pub params: &'a [Value],
    /// Public input signal names (emitted as `{public[...]}` when non-empty).
    pub pubs: &'a [String],
    /// Whether the circuit uses `pragma custom_templates`.
    pub uses_custom_templates: bool,
}

/// Generate the circom source code for a main component.
///
/// The generated file includes the pragma, an include directive (relative from
/// `main/` up to the circuit file), and the `component main` declaration.
pub fn make_circuit_source(spec: &MainComponentSpec<'_>, version: &str) -> String {
    let mut source = String::new();

    source.push_str("// auto-generated by circomkit\n");
    source.push_str(&format!("pragma circom {version};\n"));

    if spec.uses_custom_templates {
        source.push_str("pragma custom_templates;\n");
    }

    source.push_str(&format!("include \"../{}.circom\";\n\n", spec.file));

    // component main declaration
    source.push_str("component main");

    if !spec.pubs.is_empty() {
        source.push_str(&format!(" {{public[{}]}}", spec.pubs.join(", ")));
    }

    source.push_str(&format!(
        " = {}({});\n",
        spec.template,
        spec.params
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(", ")
    ));

    source
}

/// Write the main component circom file to disk.
///
/// Creates the target directory if it doesn't exist.
pub fn instantiate_circuit(
    spec: &MainComponentSpec<'_>,
    target_path: &Path,
    version: &str,
) -> std::io::Result<()> {
    let source = make_circuit_source(spec, version);

    if let Some(parent) = target_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Idempotent write: if the on-disk content is already identical, leave the
    // file (and its mtime) untouched so the compile mtime-cache stays valid.
    // When the template/params change, the content differs → the rewrite bumps
    // the mtime → `compile` recompiles instead of reusing a stale build.
    if let Ok(existing) = std::fs::read_to_string(target_path)
        && existing == source
    {
        return Ok(());
    }

    std::fs::write(target_path, source)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn basic_circuit_source() {
        let spec = MainComponentSpec {
            file: "multiplier",
            template: "Multiplier",
            params: &[json!(3)],
            pubs: &[],
            uses_custom_templates: false,
        };

        let source = make_circuit_source(&spec, "2.1.0");
        assert!(source.contains("pragma circom 2.1.0;"));
        assert!(source.contains("include \"../multiplier.circom\";"));
        assert!(source.contains("component main = Multiplier(3);"));
        assert!(!source.contains("custom_templates"));
    }

    #[test]
    fn circuit_with_public_signals() {
        let spec = MainComponentSpec {
            file: "arrays",
            template: "Arrays",
            params: &[json!(2), json!(3)],
            pubs: &["in1D".to_string(), "in2D".to_string()],
            uses_custom_templates: false,
        };

        let source = make_circuit_source(&spec, "2.1.0");
        assert!(source.contains("{public[in1D, in2D]}"));
        assert!(source.contains("= Arrays(2, 3);"));
    }

    #[test]
    fn circuit_with_custom_templates() {
        let spec = MainComponentSpec {
            file: "custom",
            template: "Custom",
            params: &[],
            pubs: &[],
            uses_custom_templates: true,
        };

        let source = make_circuit_source(&spec, "2.1.0");
        assert!(source.contains("pragma custom_templates;"));
    }
}
